---
title: "Workouts - EDA"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(googlesheets)
library(lubridate)

SHEET_NAME <- "Workout Tracker (Responses)"
colnames <- c(
  time = "Timestamp",
  track = "Track number/name",
  warmup = "Weights [warmup]",
  squats = "Weights [squats]",
  chest = "Weights [chest]",
  back = "Weights [back]",
  triceps = "Weights [triceps]",
  biceps = "Weights [biceps]",
  lunges = "Weights [lunges]",
  shoulders = "Weights [shoulders]",
  abs = "Weights [abs]",
  sets_reps_weight = "Sets x Reps @ weight",
  cardio_type = "Type", # run / swim / bike
  cardio_style = "Style", # steady state or interval
  stretch = "Stretch?"
)
```


```{r}
gs_auth(new_user = TRUE) # use personal account

sheet_key <- 
  gs_ls() %>% 
  filter(sheet_title == SHEET_NAME) %>% 
  pull(sheet_key)

df <- 
  gs_key(sheet_key) %>%
  gs_read(
    col_types = cols(
      Timestamp = col_character(),
      `Workout type` = col_character(),
      Duration = col_double(),
      Program = col_character(),
      `Track number/name` = col_character(),
      `Weights [warmup]` = col_number(),
      `Weights [squats]` = col_number(),
      `Weights [chest]` = col_number(),
      `Weights [back]` = col_number(),
      `Weights [triceps]` = col_number(),
      `Weights [biceps]` = col_number(),
      `Weights [lunges]` = col_number(),
      `Weights [shoulders]` = col_number(),
      `Weights [abs]` = col_number(),
      `Sets x Reps @ weight` = col_character(),
      Type = col_character(),
      Style = col_character(),
      Distance = col_double(),
      Description = col_character(),
      `Stretch?` = col_character(),
      `Stretch duration` = col_number()
    )
  ) %>% 
  rename(!!colnames) %>%
  janitor::clean_names()
```

```{r}
df <-
  df %>%
  mutate(
    time = mdy_hms(time),
    date = as_date(time),
    stretch = (stretch == "Yes")
  )
```

# Time series of duration of workout over the past two weeks (could have other periods of time)

```{r}
df %>%
  group_by(date) %>%
  summarize(duration = sum(duration, na.rm = TRUE)) %>%
  ggplot(aes(date, duration)) +
  geom_col() +
  geom_line(color = "red") +
  scale_x_date(date_breaks = "1 days", date_labels = "%b %d") +
  scale_y_continuous(
    breaks = seq(0, 90, by = 15), 
    labels = function(x) str_c(x, " min")
  ) +
  theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
  labs(x = NULL, y = "Total Duration of Exercise")
```

# What type of exercise have I been doing? (Also allow to filter to recent)

```{r}
df %>%
  mutate(
    type = case_when(
      workout_type == "Les Mills On Demand" ~ program,
      workout_type == "Run/Walk/Bike/Swim" ~ as.character(glue::glue("{cardio_type} ({cardio_style})")),
      TRUE ~ program
    )
  ) %>%
  group_by(type) %>%
  summarize(duration = sum(duration)) %>%
  ggplot(aes(reorder(type, -duration), duration)) +
  geom_col() +
  labs(
    x = NULL,
    y = "Total Minutes"
  )
```


