---
title: "Workouts Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(googlesheets)
library(lubridate)

file_data <- here::here("data/workouts.rds")
colors <- c(
  "Strength" = "#ff7f00",
  "Core" = "#984ea3",
  "Cardio - High intensity" =  "#4daf4a",
  "Cardio - Steady state" = "#377eb8",
  "Other" = "#e41a1c"
)

core <- c("CXWORX", "Les Mills Barre", "Bodyflow")
cardio <- c("Bodyattack", "The Trip", "Bodycombat", "Les Mills Sprint", "Les Mills Grit")

#==============

df <- read_rds(file_data)
```

Column {data-width=550}
-----------------------------------------------------------------------

### How much have you worked out in the past fortnight?

```{r}
df %>%
  mutate(
    category = case_when(
      workout_type == "Weights" ~ "Strength",
      program == "Bodypump" ~ "Strength",
      program %in% core ~ "Core",
      program %in% cardio ~ "Cardio - High intensity",
      cardio_style == "Steady state" ~ "Cardio - Steady state",
      workout_type == "Run/Walk/Bike/Swim" ~ "Cardio - High intensity",
      workout_type == "Stretch" ~ "Stretch",
      TRUE ~ "Other"
    )
  ) %>% 
  filter(date > today() - days(13)) %>% 
  ggplot(aes(date, duration)) +
  geom_col(aes(fill = category), position = "stack") +
  geom_vline(xintercept = today()) +
  scale_x_date(
    date_breaks = "1 days", 
    date_labels = "%a, %b %d",
    limits = c(today() - days(13), today())
  ) +
  scale_y_continuous(
    breaks = seq(0, 120, by = 15), 
    labels = function(x) str_c(x, " min")
  ) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(hjust = 1, angle = 45),
    legend.position = "bottom"
  ) +
  labs(
    x = NULL, 
    y = "Total Duration of Exercise",
    fill = NULL
  )
```

### All workouts to date

```{r}
df %>%
  mutate(
    category = case_when(
      workout_type == "Weights" ~ "Strength",
      program == "Bodypump" ~ "Strength",
      program %in% core ~ "Core",
      program %in% cardio ~ "Cardio - High intensity",
      cardio_style == "Steady state" ~ "Cardio - Steady state",
      workout_type == "Run/Walk/Bike/Swim" ~ "Cardio - High intensity",
      workout_type == "Stretch" ~ "Stretch",
      TRUE ~ "Other"
    )
  ) %>% 
  ggplot(aes(date, duration)) +
  geom_col(aes(fill = category), position = "stack") +
  geom_vline(xintercept = today()) +
  scale_x_date(
    date_breaks = "7 days", 
    date_labels = "%b %d"
  ) +
  scale_y_continuous(
    breaks = seq(0, 120, by = 15), 
    labels = function(x) str_c(x, " min")
  ) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.position = "bottom"
  ) +
  labs(
    x = NULL, 
    y = "Total Duration of Exercise",
    fill = NULL
  )
```

Column {data-width=450}
-----------------------------------------------------------------------

### Favorite Programs

```{r}
df %>%
  mutate(
    type = case_when(
      workout_type == "Les Mills On Demand" ~ program,
      workout_type == "Run/Walk/Bike/Swim" ~ as.character(glue::glue("{cardio_type} ({cardio_style})")),
      TRUE ~ program
    )
  ) %>%
  group_by(workout_type, type) %>%
  summarize(duration = sum(duration)) %>%
  ggplot(aes(reorder(type, duration), duration)) +
  geom_col(aes(fill = workout_type)) +
  scale_fill_manual(values = colors) +
  coord_flip() +
  theme_minimal() +
  theme(
    legend.position = "bottom"
  ) +
  labs(
    x = NULL,
    y = "Total Minutes",
    fill = NULL
  )
```

### Your Recent Workouts

```{r}
df %>%
  mutate(
    type = case_when(
      workout_type == "Les Mills On Demand" ~ str_c(program, " ", track),
      workout_type == "Run/Walk/Bike/Swim" ~ as.character(glue::glue("{cardio_type} ({cardio_style})")),
      TRUE ~ program
    ),
    stretch_duration = if_else(stretch, stretch_duration, 0)
  ) %>%
  select(
    Date = date, 
    `Workout Type` = type, 
    `Duration (minutes)` = duration, 
    `Stretch duration (minutes)` = stretch_duration
  ) %>% 
  arrange(desc(Date)) %>% 
  DT::datatable()
```

